apps/playground/package.json, apps/playground/src/editor.tsx, apps/playground/src/wait.ts, packages/editor/src/editor/Editable.tsx, pnpm-lock.yaml
Before this change, the paste operation would always be wrapped in a Promise
even when the `onPaste` handler didn't return anything. The
`if (result && result.insert) {` condition would then check if the result of
the paste handler was meaningful and if not we would default to pasting
normally, reading from the `clipboardData`. However, at this point the
`clipboardData` might already be empty. In fact, this is the case in Firefox
even for immediately resolved Promises, causing paste to not work at all if
your `onPaste` handler returned `undefined`. Now, we only wrap the paste
operation in a promise if the `onPaste` handler returns something.
=> fix: native paste operations in Firefox

packages/editor/package.json, pnpm-lock.yaml
The sanity project uses the debug module at version `^4.3.4`, while the editor is using `^3.2.7`. There aren't any breaking changes between these two apart from very old node versions not being supported anymore. By aligning on the version range, we reduce the amount of duplicate dependencies in our dependency tree.
=> fix(deps): upgrade debug module to align with sanity repo

apps/playground/src/editor.tsx, apps/playground/src/playground-machine.ts
Before this change, the editor machine didn't do anything with incoming patches. Now, the machine emits the patches and in turn, the `Editor` component listens to that event and passes the patches into the `patches$` observable.
Patch `origin` is now also properly overwritten by moving the overwrite under the spread.
=> chore(playground): make patches work

packages/editor/src/editor/Editable.tsx, packages/editor/src/types/editor.ts
Before this change, nothing would happen if you returned `undefined` wrapped in a `Promise` from the paste handler. Now, we treat this as a signal to fall back and paste normally by passing `event.clipboardData` to the internal `.insertData(...)` method. This resembles how the paste handler control flow functioned before https://github.com/portabletext/editor/pull/28. However, returning `Promise(undefined)` is not encouraged since it doesn't do what you expect in Firefox. In Firefox, the `clipboardData` isn't available anymore after the Promise microtask.
=> fix(editor): allow returning Promise(undefined) in paste handler

packages/editor/src/editor/Editable.tsx
1. Focus the editor
2. Toggle a mark
3. Press ENTER
Before this commit, the page would freeze because of an infinite loop inside `slate-react` which would keep adding decorations to the current range. Returning a new array from our custom `decorate` function fixes this problem.
See also: https://github.com/ianstormtaylor/slate/issues/3354
=> fix(editor): mitigate infinite loop which causes editor to freeze

packages/editor/src/editor/plugins/createWithHotKeys.ts
Before this change, pressing DELETE in the beginning of a text block, before a custom block (void element), would delete the entire text block and select the custom block. Now, this behaviour is only triggered if the focused text block is empty.
=> fix(editor): prevent deleting non-empty text block on DELETE

packages/editor/.eslintrc.cjs, packages/editor/src/editor/__tests__/insert-block.test.tsx, packages/editor/src/editor/plugins/createWithEditableAPI.ts
Before this change, the insert position of the new block would be off-by-one, so if you had an editor containing
```
[empty text block]
[custom block]
```
then the new block would end up after the existing custom block:
```
[custom block]
[new custom block]
```
=> fix(editor): insertBlock now properly replaces empty text blocks

packages/editor/src/editor/__tests__/insert-block.test.tsx, packages/editor/src/editor/plugins/createWithEditableAPI.ts
Instead of throwing an error, we might as well try and do what the user expects.
=> fix(editor): allow inserting block without a selection

packages/editor/e2e-tests/__tests__/annotations.test.ts, packages/editor/src/editor/plugins/createWithPortableTextMarkModel.ts, packages/editor/src/utils/withPreserveKeys.ts
Before this change, the editor would crash if you tried to undo deleting part
of an annotated text (from behind). This is because undoing the `remove_text`
operation results in an `insert_text` operation. And we have special logic in
place to make sure that `insert_text` right after annotated text results in a
new node without annotations. This not only results in an invalid state (we
didn't want to the node to be split), but it also results in a subsequent crash
when the selection stored on the undo stack would try to select inside the
unsplit node.
=> fix(editor): allow undoing part-deletion of annotated text

packages/editor/src/editor/plugins/createWithUndoRedo.ts
Before this change, if either undoing or redoing threw an error, the editor would be stuck in the "preserve keys" state, causing duplicate keys to appear everywhere, cascading into all sorts of problems and disruptive typing.
=> fix(editor): guard against erroneous undo/redo

packages/editor/e2e-tests/__tests__/annotations.test.ts, packages/editor/src/editor/plugins/createWithPortableTextMarkModel.ts
There were a couple of problems with the code before this change:
1. Merge spans normalisation would only be run on spans and as a result of
specific operations.
2. Merge spans normalisation could run on spans that were already removed.
Now, the normalisation logic is structured as normalisation logic would
normally be structured. It's the parent block that takes care of merging spans
and the normalisation is run whenever the editor deems that it's time to run
normalisation. This makes sure that all spans in the editor at all times are
normalised, not just those that were touched by a specific operation. This
takes care of both problem (1) and (2). We now also don't run
`editor.onChange()` after custom normalisation anymore. Instead, we `return` to
trigger a new normalisation pass.
=> fix(editor): fix merge spans normalisation logic

packages/editor/e2e-tests/__tests__/annotations-across-blocks.feature, packages/editor/e2e-tests/__tests__/annotations-overlapping-decorators.feature, packages/editor/e2e-tests/__tests__/annotations-overlapping.feature, packages/editor/src/editor/PortableTextEditor.tsx, packages/editor/src/editor/plugins/createWithEditableAPI.ts, packages/editor/src/types/editor.ts
Before this change, adding an annotation to a cross-block selection would only
apply it to the focus block (the block which the focus point of the selection
points to). Additionally, when adding the annotation to the selected spans of
said block, all existing decorators and annotations would be removed in the
process.
Now, annotations can be added across blocks and on top of existing decorators
and annotations.
It's worth noting that:
- Adding an annotation across blocks essentially creates copies of the
annotation. Each `markDef` is given its own unique key.
- Adding an annotation across another annotation of the same type will remove
the part of the existing annotation which is selected. (Two links on the same
text doesn't make sense, similar to how you can't double-bold a piece of …
=> feat(editor): support annotations across blocks, annotations and decorators

packages/editor/e2e-tests/__tests__/gherkin-driver.ts
I don't think this URI is important, but it still looks bad to hardcode it.
=> test(editor): remove accidentally hardcoded URI

packages/editor/e2e-tests/__tests__/annotations-across-blocks.feature, packages/editor/e2e-tests/__tests__/annotations-collaboration.feature, packages/editor/e2e-tests/__tests__/annotations-collaboration.test.ts, packages/editor/e2e-tests/__tests__/annotations-edge-cases.feature, packages/editor/e2e-tests/__tests__/annotations-overlapping-decorators.feature, packages/editor/e2e-tests/__tests__/annotations-overlapping.feature, packages/editor/e2e-tests/__tests__/annotations.feature, packages/editor/e2e-tests/__tests__/annotations.test.ts, packages/editor/e2e-tests/__tests__/block-objects.feature, packages/editor/e2e-tests/__tests__/block-objects.test.ts, packages/editor/e2e-tests/__tests__/decorators.feature, packages/editor/e2e-tests/__tests__/decorators.test.ts, packages/editor/e2e-tests/__tests__/gherkin-step-definitions.ts, packages/editor/e2e-tests/__tests__/inline-objects.feature, packages/editor/e2e-tests/__tests__/inline-objects.test.ts, packages/editor/e2e-tests/__tests__/removing-blocks.feature, packages/editor/e2e-tests/__tests__/removing-blocks.test.ts, packages/editor/e2e-tests/__tests__/splitting-blocks.feature, packages/editor/e2e-tests/__tests__/splitting-blocks.test.ts, packages/editor/e2e-tests/__tests__/undo-redo-collaboration.feature, packages/editor/e2e-tests/__tests__/undo-redo-collaboration.test.ts, packages/editor/e2e-tests/__tests__/undo-redo.feature, packages/editor/e2e-tests/setup/collaborative.jest.env.ts, packages/editor/e2e-tests/setup/get-page-editor.ts, packages/editor/e2e-tests/setup/globals.jest.ts, packages/editor/e2e-tests/setup/jest.env.ts
In an effort to reduce the flakiness of the tests, we now only run tests with multiple pages (multiple editors) when needed.
=> test: only run the collaborative env when needed

packages/editor/src/editor/__tests__/self-solving.test.tsx, packages/editor/src/editor/editor-machine.ts, packages/editor/src/editor/plugins/createWithObjectKeys.ts, packages/editor/src/editor/plugins/createWithPortableTextBlockStyle.ts, packages/editor/src/editor/plugins/createWithPortableTextMarkModel.ts, packages/editor/src/editor/plugins/createWithSchemaTypes.ts, packages/editor/src/editor/plugins/index.ts, packages/editor/src/index.ts
Before this change, `patch` and `mutation` changes/events could be emitted from
the editor even if no edits had been made. This could happen happen if the
editor was instantiated with a value that didn't adhere to the format and
therefore got normalized as soon as it entered the editor (e.g. `.mardDefs`
added to blocks). To mitigate this, we now defer these events as long as they
happen as part of the initial normalization process. As soon as a single
`patch` (or `mutation`, but probably not) happens out side of the
`normalization` state, we assume the editor is dirty. From this point we
emit all pending events and immediately emit all other events going forward.
=> fix(editor): defer patch/mutation changes until the editor is dirty

packages/editor/e2e-tests/__tests__/annotations-overlapping-decorators.feature, packages/editor/e2e-tests/__tests__/annotations-overlapping.feature, packages/editor/e2e-tests/__tests__/decorators.feature, packages/editor/src/editor/plugins/createWithInsertBreak.ts, packages/editor/src/editor/plugins/createWithPortableTextMarkModel.ts
This change covers even more scenarios related to inserting text before or
after an annotation. It is well known that text inserted after a link will not
be put inside that link. But this change takes this concept a bit further and
makes sure that any decorators inside the link won't leak either. This treats
the annotation as a proper boundary.
This change also fixes some inconsistencies related to inserting text
before/after overlapping annotations.
=> fix(editor): treat annotations as proper boundaries

packages/editor/src/editor/Editable.tsx, packages/editor/src/editor/behavior/behavior.actions.ts, packages/editor/src/editor/behavior/behavior.core.ts, packages/editor/src/editor/behavior/behavior.types.ts, packages/editor/src/editor/editor-machine.ts, packages/editor/src/editor/plugins/create-with-event-listeners.ts, packages/editor/src/editor/plugins/index.ts
Instead of hooking into native events we now hook into bespoke "Slate events". This is not only provides a cleaner Behavior API. It's also more correct since you don't have to figure out yourself what native events might correspond to events like `insert break` and `delete backward`.
=> refactor(editor): refactor Behavior API

packages/editor/src/editor/behavior/behavior.action.insert-break.ts, packages/editor/src/editor/behavior/behavior.actions.ts, packages/editor/src/editor/behavior/behavior.core.ts, packages/editor/src/editor/behavior/behavior.types.ts, packages/editor/src/editor/editor-machine.ts, packages/editor/src/editor/plugins/create-with-event-listeners.ts, packages/editor/src/editor/plugins/createWithInsertBreak.ts, packages/editor/src/editor/plugins/index.ts, packages/editor/src/index.ts
Cleans up the internal Behavior API, mitigates some (unobtrusive) loops and as
a bonus also allows behavior actions to be defined in sets. The idea is that
each set of actions is its own undo step and run without normalisation. The
undo part seems to not quite work yet, however. Will revisit.
Another bonus of this commit is that it changes how we overwrite the built-in
`insertBreak` functionality. Instead creating a Slate plugin we just define the
custom functionality as the default behavior action.
=> fix(editor): refactor internal Behavior API

packages/editor/src/editor/components/Synchronizer.tsx
Resolves this warning:
```
Ref values (the `current` property) may not be accessed during render. (https://react.dev/reference/react/useRef)
```
Which is thrown because [`onFlushPendingPatchesThrottled`](https://github.com/portabletext/editor/blob/b586f249dc79d0bab09e3b91261877645ff8c8ec/packages/editor/src/editor/components/Synchronizer.tsx#L72), wrapped in `useMemo`, is calling [`onFlushPendingPatches‎()`](https://github.com/portabletext/editor/blob/b586f249dc79d0bab09e3b91261877645ff8c8ec/packages/editor/src/editor/components/Synchronizer.tsx#L78), which is using a [reference](https://github.com/portabletext/editor/blob/b586f249dc79d0bab09e3b91261877645ff8c8ec/packages/editor/src/editor/components/Synchronizer.tsx#L64).
This is technically a false negative by the compiler, but seeing …
=> fix(performance): allow `Synchronizer` to be compiled

packages/editor/package.json, pnpm-lock.yaml
Note: This is currently breaking `sanity@next`.
[This line](https://github.com/portabletext/editor/blob/995bbe5e43f62061c4ebe8a71403c26c2a3acbea/packages/editor/src/editor/use-editor.ts#L6) is importing from `@xstate/react`, which is marked as a dev dependency - not a production dependency, so it is not installed for most applications.
=> fix: move `@xstate/react` from dev to production dependency

.github/workflows/react-compiler.yml, packages/editor/package.json
The official schedule is every monday at 9AM. So it's unnecessary for our workflow to run every day, I've changed it to run 3 hours after theirs so it's likely that their release pipeline have finished by then.
Also enabled expanded reporting by the linter so we know if it's bailing out due to other reasons than hook violations, for example due to not yet supporting a specific pattern (like try/catch).
=> chore: adjust react compiler linter and cron schedule

packages/editor/src/editor/PortableTextEditor.tsx, packages/editor/src/editor/create-slate-editor.tsx
This fixes an issue where the Slate editor could be torn down from within `PortableTextEditor` (if it unmounted and mounted again) and never set properly up again. To avoid writing setup logic for the editor, it feels simpler and more robust to just tear it down if the `EditorActor` is stopped.
=> fix: move Slate editor teardown logic to createSlateEditor

packages/editor/package.json, packages/editor/src/editor/plugins/createWithHotKeys.ts, packages/editor/src/utils/is-hotkey.test.ts, packages/editor/src/utils/is-hotkey.ts, pnpm-lock.yaml
We didn't use all the functions from the external `is-hotkey-esm` package and
the external package didn't have tests either. Those are pulled from
https://github.com/ianstormtaylor/is-hotkey.
=> fix(deps): inline and simplify `isHotkey` dependency

packages/editor/src/editor/behavior/behavior.actions.ts, packages/editor/src/editor/behavior/behavior.types.ts, packages/editor/src/editor/editor-machine.ts, packages/editor/src/index.ts
Holding down an arrow key to go up and down through the editor text was
noticeably slow before this change. Now, we separate native and synthetic
behavior events and bail out quicker if a native event shouldn't be handled.
`NativeBehaviorEvent`s simply don't have default actions anymore. Which makes a
lot of sense since they were noops in the first place.
=> fix(performance regression): bail out quicker on native behavior events

packages/editor/src/editor/__tests__/RangeDecorations.test.tsx, packages/editor/src/editor/__tests__/pteWarningsSelfSolving.test.tsx, packages/editor/src/editor/sync-machine.ts
If the initial value is thousands of blocks long, it will block the main thread
while syncing. Therefore, we now stream the initial value, making the process
interruptable.
One caveat: We only stream the **initial** value, not incoming subsequent
values. It's simply too complicated right now to stream subsequent values since
we can't be sure that user actions don't interfere with the process. The reason
we can safely stream the initial value is that we can make the editor read-only
while that happens.
=> fix(perf): stream the initial value into the editor

apps/docs/src/styles/globals.css, apps/docs/tailwind.config.mjs
This removes the shadcn styling to body, thus fixing the Starlight theme dark mode
=> fix: disable shadcn base colors to fix dark mode

apps/docs/src/content/docs/guides/behavior-cheat-sheet.mdx
Guard needs to return true or a value for the actions to work.
=> docs(fix): fix logic in autoCloseParens example

apps/docs/src/components/editor/toolbar.tsx, apps/docs/src/content/docs/reference/behavior-api.mdx, apps/playground/src/portable-text-toolbar.tsx, examples/basic/src/App.tsx, packages/editor/gherkin-tests/editors.tsx, packages/editor/src/behavior-actions/behavior.actions.ts, packages/editor/src/behaviors/behavior.types.ts, packages/editor/src/editor/create-editor.ts, packages/editor/src/editor/editor-machine.ts, packages/editor/src/editor/plugins/create-with-event-listeners.ts
These are potentially confusing because `annotation.toggle` doesn't trigger
`annotation.add` or `annotation.remove` events and `decorator.toggle` doesn't
trigger `decorator.add` or `decorator.remove`. Therefore, it feels more
intuitive to remove `annotation.toggle` while keeping
`annotation.add`/`annotation.remove` and remove
`decorator.add`/`decorator.remove` while keeping `decorator.toggle`.
`annotation.toggle`, `decorator.add` and `decorator.remove` still exist as
built-in actions that can be performed.
=> fix(behavior): remove `annotation.toggle` and `decorator.(add|remove)` events

apps/docs/astro.config.mjs, apps/docs/src/content/docs/reference/behavior-api.mdx, apps/docs/src/content/docs/reference/editor.mdx, apps/docs/src/content/docs/reference/selectors.mdx, packages/editor/package.config.ts, packages/editor/src/behaviors/behavior.markdown.ts, packages/editor/src/behaviors/behavior.types.ts, packages/editor/src/editor/Editable.tsx, packages/editor/src/editor/define-schema.ts, packages/editor/src/editor/editor-event-listener.tsx, packages/editor/src/editor/editor-provider.tsx, packages/editor/src/editor/editor-selector.ts
Updates the typedoc setup to be a bit cleaner. This should allow us to annotate in code, and have somewhat stable reference links.
=> docs: add more details to typedoc support

packages/editor/src/editor/PortableTextEditor.tsx, packages/editor/src/editor/sync-machine.ts
Before this change, the sync machine would not reenter the `busy` state and
thus it wouldn't restart the 1000ms interval to check the busy state again.
This meant that if the machine tried to sync a value at the same time as
concurrent edits were happening, the machine would get stuck and never leave
the `busy` state. Specifying the `target` of the transition solves this issue.
=> fix: make sure value sync is retried when busy

packages/editor/src/selectors/selector.get-selected-spans.test.ts, packages/editor/src/selectors/selector.get-selected-spans.ts, packages/editor/src/selectors/selector.is-active-annotation.ts
Before this change, the `getSelectedSpans` selector would include start and
end spans of a selection even if they were right at the edge of a selection.
Not only is this unexpected (the text of the spans is not visually selected),
it also results in other issues downstream. For example, the
`isActiveDecorator` would return `false` for a decorator that is clearly
(visually) active in the current selection.
`isActiveAnnotation` also needs to be adjusted as a result of this change. It
is expected that you can toggle an annotation with a collapsed selection, so in
this case we need to use `getFocusSpan` instead of `getSelectedSpan`.
=> fix(selector.getSelectedSpans): don't include spans at the edge of a selection

packages/block-tools/src/HtmlDeserializer/index.ts, packages/block-tools/src/HtmlDeserializer/rules/html.ts, packages/block-tools/test/html-to-blocks/blockquote.test.ts, packages/block-tools/test/tests/HtmlDeserializer/customRules/output.json, packages/block-tools/test/tests/HtmlDeserializer/nestedContainers/output.json
Before this change, each line break in a blockquote would be double (`\n\n`).
And if the HTML had whitespace, it could potentially yield four line breaks
between each line of text. Now, only a single line break is added between lines
of text in a blockquote.
**Real-world scenario:**
In Notion, it's somehow possible to end up with two merged blockquotes (I'm actually not exactly sure how to do this, I just copy/pasted the example from another Notion document that prompted this fix):
Copying that puts the following HTML on the clipboard:
```html
<meta charset='utf-8'><blockquote>
<p>foo bar baz</p>
<p>fizz buzz</p>
</blockquote>
```
Pasting this would previously yield:
But now it yields:
=> fix(block-tools): ensure single line breaks in blockquotes

packages/racejar/example/hello-herman.test.ts, packages/racejar/src/compile-feature.ts
This adds support for Data Tables and DocStrings.
I deliberately did not create a `DataTable` class (as in the original `@cucumber/cucumber`).
I think it's better to keep this out of the library.
I really like what you have done with racejar - making it possible to use Cucumber from other test runners.
Would you be open to extracting racejar to a separate repo?
I have started using Racejar for a my startup (openartmarket.com), so I would be interested in some level of co-maintenance.
I'm the original creator of Cucumber, but I haven't been involved with it for a few years now.
There is an active group of maintainers of Cucumber in the `cucumber` GitHub org, and if they are open to it, we could host the repo there (if everyone agrees). /cc @davidjgoss
=> feat: Add support for Data Tables and DocStrings

packages/racejar/example/hooks.test.ts, packages/racejar/src/compile-feature.ts, packages/racejar/src/hooks.ts, packages/racejar/src/index.ts, packages/racejar/src/jest/jest-gherkin-driver.ts, packages/racejar/src/playwright/playwright-gherkin-driver.ts, packages/racejar/src/vitest/vitest-gherkin-driver.ts
This adds support for Before and After hooks.
Cucumber allows for scoping of hooks via tags - I have not added this in this PR.
Hooks are useful for setting up context (such as clearing a database).
=> feat: add support for Before and After hooks

packages/editor/src/behaviors/behavior.markdown-emphasis.ts, packages/editor/src/internal-utils/get-text-to-emphasize.test.ts, packages/editor/src/internal-utils/get-text-to-emphasize.ts
I had forgot a `$` for the first part of each regex so `*Hello*world*` would result in `*Hello*` as a match, not `*world*`. This has now been fixed and unit tests have been added.
=> fix(markdown emphasis): fix edge case producing wrong match

packages/editor/src/behavior-actions/behavior.actions.ts
The `deleteBackward` method on the `editor` object contains special handling for line deletion. If we use the `deleteBackward` transformation directly, we miss out on that.
https://github.com/ianstormtaylor/slate/blob/7a8ab18c527c97aebcafe5b88032da38aa1664b0/packages/slate-dom/src/plugin/with-dom.ts#L93
=> fix: make sure Mod+Backspace can delete line

apps/playground/package.json, examples/basic/package.json, examples/legacy/package.json, packages/editor/package.json, packages/editor/src/editor/PortableTextEditor.tsx, packages/editor/src/plugins/plugin.event-listener.tsx, pnpm-lock.yaml
The experimental version of `eslint-plugin-react-hooks` now handles `useEffectEvent` correctly
=> chore: use `useEffectEvent` aware linting

packages/editor/src/behavior-actions/behavior.action.block.set.ts, packages/editor/src/behavior-actions/behavior.action.block.unset.ts, packages/editor/src/behaviors/behavior.types.ts, packages/editor/src/internal-utils/parse-blocks.ts, packages/editor/tests/event.block.set.test.tsx, packages/editor/tests/event.block.unset.test.tsx
`block.set` and `block.unset` to set/unset arbitrary props (and the _key) on block objects now works as expected. See the two commits for more detail.
=> fix: `block.(set|unset)`

packages/editor/src/converters/converter.text-plain.test.ts, packages/editor/src/internal-utils/create-test-snapshot.ts, packages/editor/src/selectors/selector.get-active-annotations.test.ts, packages/editor/src/selectors/selector.get-caret-word-selection.test.ts, packages/editor/src/selectors/selector.get-selected-spans.test.ts, packages/editor/src/selectors/selector.get-selection-text.test.ts, packages/editor/src/selectors/selector.get-trimmed-selection.test.ts, packages/editor/src/selectors/selector.is-active-decorator.test.ts
To avoid referencing and hand-rolling `EditorSnapshot` too many places.
=> test: add `createTestSnapshot`

packages/editor/package.json, packages/editor/src/behaviors/behavior.decorator-pair.ts, packages/editor/src/behaviors/index.ts, packages/editor/src/converters/converter.text-html.serialize.test.ts, packages/editor/src/converters/converter.text-plain.test.ts, packages/editor/src/internal-utils/create-test-snapshot.ts, packages/editor/src/plugins/plugin.decorator-shortcut.ts, packages/editor/src/selectors/index.ts, packages/editor/src/selectors/selector.get-active-annotations.test.ts, packages/editor/src/selectors/selector.get-caret-word-selection.test.ts, packages/editor/src/selectors/selector.get-selected-spans.test.ts, packages/editor/src/selectors/selector.get-selection-end-point.ts, packages/editor/src/selectors/selector.get-selection-start-point.ts, packages/editor/src/selectors/selector.get-selection-text.test.ts, packages/editor/src/selectors/selector.get-selection.ts, packages/editor/src/selectors/selector.get-value.ts, packages/editor/src/selectors/selector.is-active-decorator.test.ts, packages/editor/src/utils/index.ts, packages/editor/src/utils/util.block-offsets-to-selection.ts, packages/editor/src/utils/util.is-span.ts, packages/editor/src/utils/util.is-text-block.ts, packages/editor/src/utils/util.merge-text-blocks.ts, packages/editor/src/utils/util.slice-blocks.ts, packages/editor/src/utils/util.split-text-block.ts
`/behaviors`, `/selectors` and `/utils` shouldn't reexport types from the main
export. This is confusing, unnecessary and easily creates cyclic dependencies.
=> fix(types): remove cyclic dependencies

packages/editor/src/editor/sync-machine.ts
By syncing 10 blocks at a time. It's unbearably slow to sync large docs, but this *should* give a speed increase without tanking perf.
=> fix: speed up initial value sync

packages/editor/gherkin-tests/hand-coded.test.tsx, packages/editor/src/editor/Editable.tsx, packages/editor/src/editor/__tests__/RangeDecorations.test.tsx, packages/editor/src/editor/range-decorations-machine.ts
An `updateCount` is used to rerender `Editable` whenever then incoming range decorations are different than the existing range decorations (compared to their selection). Moving range decorations work exactly like before, but a test is now failing. This tests has been skipped and will be revisted later.
=> fix: trigger rerender when range decorations change

packages/editor/src/editor/Editable.tsx, packages/editor/src/editor/range-decorations-machine.ts
Some scenarios with running PTE in dev mode can potentially rerender `Editable` and recreate the range decorations machine. At this point the `ready` event might already have been fired so the new range decorations machine never gets set up properly. This fix mitigates this scenario by checking the state of the editor machine to see if we can skip the setup step (since in that case the `ready` event won't fire)
=> fix: allow skipping range decoration setup

packages/editor/src/editor/__tests__/PortableTextEditor.test.tsx, packages/editor/src/editor/__tests__/PortableTextEditorTester.tsx, packages/editor/src/editor/__tests__/RangeDecorations.test.tsx, packages/editor/src/editor/__tests__/pteWarningsSelfSolving.test.tsx, packages/editor/src/editor/__tests__/sync-value.test.tsx, packages/editor/src/editor/plugins/__tests__/withEditableAPIDelete.test.tsx, packages/editor/src/editor/plugins/__tests__/withEditableAPIGetFragment.test.tsx, packages/editor/src/editor/plugins/__tests__/withEditableAPIInsert.test.tsx, packages/editor/src/editor/plugins/__tests__/withEditableAPISelectionsOverlapping.test.tsx, packages/editor/src/editor/plugins/__tests__/withPortableTextLists.test.tsx, packages/editor/src/editor/plugins/__tests__/withPortableTextMarkModel.test.tsx, packages/editor/src/editor/plugins/__tests__/withPortableTextSelections.test.tsx, packages/editor/src/editor/plugins/__tests__/withUndoRedo.test.tsx, packages/editor/src/internal-utils/__tests__/valueNormalization.test.tsx
Some mark model tests that were troublesome to adjust and which are covered elsewhere have also been removed.
=> test: use test key generator in old tests

apps/docs/src/content/docs/concepts/behavior.mdx, apps/docs/src/content/docs/guides/behavior-cheat-sheet.mdx, apps/docs/src/content/docs/guides/create-behavior.mdx, apps/playground/src/emoji-picker.tsx, packages/editor/src/behaviors/behavior.decorator-pair.ts, packages/editor/src/behaviors/behavior.emoji-picker.ts, packages/editor/src/behaviors/behavior.links.ts, packages/editor/src/behaviors/behavior.markdown.ts, packages/editor/src/behaviors/behavior.perform-event.ts, packages/editor/src/behaviors/behavior.types.action.ts, packages/editor/src/behaviors/index.ts, packages/editor/src/editor/editor-machine.ts, packages/editor/src/plugins/plugin.decorator-shortcut.ts, packages/editor/src/plugins/plugin.one-line.tsx, packages/editor/tests/behavior-api.test.tsx, packages/editor/tests/editor-snapshot.test.tsx, packages/editor/tests/event.history.undo.test.tsx
This commit brings a fundamental change to Behavior Actions. Previously, each Synthetic Event had a corresponding Action that you could return in Action sets. These are the Actions that actually *do* something and which you can perform on the editor without any other Behavior interfering. This was useful, but also had two downsides:
1. The Actions looked a lot like Events (because they sort of were).
2. When returning Actions you miss out on all the useful Abstract Events. For example, if you want to do `select.previous block`, you have to `raise(...)` that which means you can't be sure another Behavior doesn't hijack the Event.
To resolve these two downsides, the Sythetic Event Actions are embraced as what they are: Synthetic Events. And in order to execute these you wrap them in …
=> feat(behaviors): replace Synthetic Event Actions with `execute`

packages/editor/src/behavior-actions/behavior.action.move.backward.ts, packages/editor/src/behavior-actions/behavior.action.move.forward.ts, packages/editor/src/behavior-actions/behavior.actions.ts, packages/editor/src/behaviors/behavior.types.event.ts
Ideally, these should be Abstract Events mapping to Synthetic `select` Events, but that would be a rather big task to implement since it would require us to do the position calculation ourselves in a Behavior instead of letting Slate do the calculation: https://github.com/ianstormtaylor/slate/blob/main/packages/slate/src/editor/positions.ts
However, in the future, it would be good to implement this ourselves.
=> feat(behaviors): add `move.backward` and `move.forward` events

packages/editor/src/internal-utils/parse-blocks.test.ts, packages/editor/src/internal-utils/parse-blocks.ts, packages/editor/tests/event.block.set.test.tsx, packages/editor/tests/event.insert.block.test.tsx
When blocks are pasted or inserted, they go through `parseBlock(...)`. This change makes sure we strip unknown fields/props from those blocks in the process.
=> fix(block parsing): strip unknown fields from text blocks

packages/editor/src/editor/range-decorations-machine.ts
The `'set up initial range decorations'` could be called with the init event, but since it asserted the `'ready'` event, this could result in a runtime error. To mitigate this, and other potential errors of the same kind, the usage of `assertEvent` has been removed in favour of early returns.
=> fix: mitigate range decoration runtime errors

packages/editor/src/editor/editor-context.tsx, packages/editor/src/editor/editor-provider.tsx, packages/editor/src/internal-utils/global-scope.ts, packages/editor/src/internal-utils/globally-scoped-context.ts
I guess it doesn't hurt to try this out.
Code more-or-less copy/pasted from https://github.com/sanity-io/ui/blob/main/src/core/lib/createGlobalScopedContext.ts
=> fix: provide `Editor` from a global Context

apps/docs/src/content/docs/guides/behavior-cheat-sheet.mdx, apps/docs/src/content/docs/reference/behavior-api.mdx, apps/docs/src/content/docs/reference/plugins.mdx, apps/playground/src/emoji-picker.tsx, apps/playground/src/plugin.image-deserializer.tsx, apps/playground/src/plugin.text-file-deserializer.tsx, packages/editor/src/behavior-actions/behavior.action.noop.ts, packages/editor/src/behavior-actions/behavior.actions.ts, packages/editor/src/behaviors/behavior.core.dnd.ts, packages/editor/src/behaviors/behavior.default.ts, packages/editor/src/behaviors/behavior.emoji-picker.ts, packages/editor/src/behaviors/behavior.perform-event.ts, packages/editor/src/behaviors/behavior.types.action.ts, packages/editor/src/behaviors/index.ts, packages/editor/src/editor/components/Element.tsx, packages/editor/src/editor/editor-machine.ts, packages/editor/src/plugins/plugin.decorator-shortcut.ts, packages/editor/src/plugins/plugin.one-line.tsx, packages/editor/tests/behavior-api.test.tsx, packages/editor/tests/event.history.undo.test.tsx
Consider this: If someone today asks "how does a Behavior affect event propagation?", then the answer would be:
It depends.
1. If your `guard` is truthy, but you didn't configure any `actions`, then the `event` is forwarded to the next Behavior.
2. If you return any Action from `actions` then your Behavior "owns" the `event.
3. Except if you only do `effect` Actions. Those will not affect the event propagation, because it should be possible to do side effects without interrupting the `event`.
4. However, if you do want to interrupt the `event` while doing the side effect, you can reach for the special `noop` action.
After the introduction of `forward` (and the removal of `noop`), the answer is:
1. If your `guard` is truthy you own the `event`.
It's that simple.
The rest of the rules are …
=> feat(behaviors): simplify event propagation by introducing `forward(event)`

packages/editor/gherkin-spec/insert.blocks.feature, packages/editor/src/behavior-actions/behavior.action.delete.ts, packages/editor/tests/event.delete.test.tsx
Slate might merge the next block into the focus block if the next block is also a text block and there's no need for this. Sending `delete` on a collapsed selection inside a span should always be a noop.
=> fix(`delete`): don't delete when having a collapsed span selection

packages/editor/src/behaviors/behavior.perform-event.ts
We have no control over the `guard` and it might throw errors. In that case it's important that they don't bring down the entire editor.
=> fix: guard against `guard` errors

packages/editor/gherkin-tests/hand-coded.test.tsx, packages/editor/src/editor/components/render-text-block.tsx
Before this change, the `children` modified by `renderListeItem` and `renderStyle` would only be returned through `renderBlock`. There seems to be no good reason to enforce this constraint and therefore it has been removed. This means that `renderStyle` or `renderListItem` can now be used in isolation without needing to worry about adding a placeholder render function like:
```tsx
renderBlock={(props) => <>{props.children}</>}
```
=> fix: allow `renderListItem`/`renderStyle` without `renderBlock`

packages/editor/src/behaviors/behavior.abstract.split.ts
The selector was incorrectly passed an adjusted value, only containing the
focus text block.
=> fix(regression): allow splitting all text blocks in the middle

packages/block-tools/package.json, packages/editor/package.json
Prepping for July 15th: https://www.sanity.io/blog/a-major-version-bump-for-a-minor-reason#299526b398ec
Currently when using a package.json like: 
```json
{
"dependencies": {
"sanity": "4.0.0-0"
}
}
```
Running `pnpm install --resolution-only` yields peer dep issues:
```bash
Progress: resolved 1025, reused 0, downloaded 0, added 0, done
 WARN  Issues with peer dependencies found
.
└─┬ sanity 4.0.0-0
└─┬ @portabletext/editor 1.57.1
├── ✕ unmet peer @sanity/types@^3.98.0: found 4.0.0-0
├── ✕ unmet peer @sanity/schema@^3.98.0: found 4.0.0-0
└─┬ @portabletext/block-tools 1.1.36
└── ✕ unmet peer @sanity/types@^3.98.0: found 4.0.0-0
```
This fixes it.
=> fix(deps): allow studio v4 in peer dep ranges

packages/block-tools/package.config.ts, packages/editor/package.config.ts, packages/keyboard-shortcuts/package.config.ts, packages/patches/package.config.ts, packages/toolbar/package.config.ts
[There's an issue in `@microsoft/api-extractor` that leads to partially broken generation of `.d.ts` files](https://github.com/microsoft/rushstack/issues/5106), [it's affecting `@portabletext/editor`](https://github.com/sanity-io/sanity/pull/9989).
By switching to `rolldown` we get healthy dts builds, [as seen in this test PR](https://github.com/sanity-io/sanity/pull/10000), and by looking at the diff output and how relative `import type from '../does-not-exist'` statements no longer appearing:
- [`@portabletext/editor`](https://npmdiff.dev/%40portabletext%2Feditor/1.58.0/2.0.0-canary.0/) – no more [`import {EditorPriority as EditorPriority_2} from '../priority/priority.types'`](https://npmdiff.dev/%40portabletext%2Feditor/1.58.0/2.0.0-canary.0/package/lib/index.d.cts)
- …
=> fix: use `rolldown` instead of `api-extractor` for dts generation

packages/editor/package.json, pnpm-lock.yaml
It was previously downgraded in
https://github.com/portabletext/editor/pull/1260, but then got upgraded again in https://github.com/portabletext/editor/pull/1444.
v2 of the package is breaking the editor in various instances. I don't have an overview of why/when it happens, but until I do, I can't upgrade the package to v2.
=> fix(deps): downgrade `use-effect-event`

packages/editor/package.json, packages/editor/src/editor-event-listener.tsx, packages/editor/src/plugins/plugin.event-listener.tsx, pnpm-lock.yaml
`editor` is stable so the only thing that could trigger a resubscription is if `props.on` changes (which is what you would want).
=> fix: remove `use-effect-event`

apps/playground/package.json, examples/basic/package.json, examples/legacy/package.json, packages/editor/package.json, packages/sanity-bridge/package.json, packages/toolbar/package.json, pnpm-lock.yaml
Node v22 added support for `require(esm)` in 22.12, we've updated the node engines semver in `sanity` and other packages to reflect this, for the same reasons we do it for `22.19`.
While here I noticed the usage of `workspace:*` and `workspace:^` is a bit inconsistent and not as optimized as it could be.
The guideline is that generally `workspace:*` should always be used, as it means the exact version.
Technically, a package like `apps/playground/package.json` isn't published to npm, so what it wants is the equivalent of `workspace:`, it wants the workspace package, whatever the version is, semver ranges doesn't matter. (That might be why the default syntax for `catalog` is `catalog:` and not `catalog:*`).
When packages are published it matters what comes after the `:`. `workspace:*` is …
=> fix: reduce peer deps duplication and set min node 22 version

apps/docs/src/content/docs/integrations/serializers.mdx
Adds a few missing serializers to the integrations doc page, and adds a blurb at the top directing users to the PT org for more.
=> docs(chore): add missing libraries to serializers list
